services:
  stats-server:
    build: ./stats-service/server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

#  ewm-service:
#    build: ./main-service
#    container_name: ewm-service-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
#      - SPRING_DATASOURCE_USERNAME=shareit
#      - SPRING_DATASOURCE_PASSWORD=shareit
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: ewm-db
#    ports:
#      - "6432:5432"
#    environment:
#      - POSTGRES_DB=ewm-db
#      - POSTGRES_USER=shareit
#      - POSTGRES_PASSWORD=shareit
